function escapePdfText(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/\(/g, "\\(").replace(/\)/g, "\\)").replace(/[\r\n]+/g, " ")
}

export function createInvoicePdf({
  invoiceId,
  company,
  clientName,
  clientEmail,
  amount,
  gstRate,
  dueDate,
  createdAt,
  includeGst,
}: {
  invoiceId: string
  company: string
  clientName: string
  clientEmail: string
  amount: number
  gstRate: number
  dueDate: Date
  createdAt: Date
  includeGst: boolean
}) {
  const gst = includeGst ? amount * (gstRate / 100) : 0
  const total = amount + gst
  const money = (n: number) => `INR ${n.toFixed(2)}`
  const date = (d: Date) => d.toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })

  const commands = [
    "q",
    "0.15 0.25 0.65 rg",
    "70 730 42 42 re f",
    "0 0 0 rg",
    "BT",
    "/F1 18 Tf",
    "125 752 Td",
    "(Company Management Dashboard) Tj",
    "/F1 10 Tf",
    "0 -18 Td",
    "(Professional services and business operations) Tj",
    "ET",
    "0.82 0.85 0.9 RG",
    "70 705 m 525 705 l S",
    "0 0 0 rg",
    "BT",
    "/F1 20 Tf",
    "70 665 Td",
    `(INVOICE #${escapePdfText(invoiceId.slice(-8).toUpperCase())}) Tj`,
    "/F1 10 Tf",
    "0 -28 Td",
    `(Billed to: ${escapePdfText(company)}) Tj`,
    "0 -15 Td",
    `(Attn: ${escapePdfText(clientName)} | ${escapePdfText(clientEmail)}) Tj`,
    "0 -32 Td",
    `(Issue date: ${escapePdfText(date(createdAt))}) Tj",
    "0 -15 Td",
    `(Due date: ${escapePdfText(date(dueDate))}) Tj`,
    "ET",
    "0.96 0.97 0.99 rg",
    "70 535 525 36 re f",
    "0 0 0 rg",
    "BT",
    "/F1 10 Tf",
    "82 548 Td",
    "(Description) Tj",
    "300 0 Td",
    "(Amount) Tj",
    "ET",
    "BT",
    "/F1 11 Tf",
    "82 512 Td",
    "(Professional services) Tj",
    "300 0 Td",
    `(${escapePdfText(money(amount))}) Tj`,
    "0 -28 Td",
    `(GST ${escapePdfText(gstRate.toFixed(2))}%) Tj`,
    "300 0 Td",
    `(${escapePdfText(money(gst))}) Tj`,
    "0 -34 Td",
    "/F1 13 Tf",
    "82 -2 Td",
    "(TOTAL) Tj",
    "300 0 Td",
    `(${escapePdfText(money(total))}) Tj`,
    "ET",
    "BT",
    "/F1 9 Tf",
    "70 360 Td",
    `(GST included: ${includeGst ? "Yes" : "No"}) Tj`,
    "0 -16 Td",
    "(Generated by Company Management Dashboard) Tj",
    "ET",
    "Q",
  ]

  const content = commands.join("\n")
  const objects = [
    "<< /Type /Catalog /Pages 2 0 R >>",
    "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
    "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
    "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    `<< /Length ${Buffer.byteLength(content, "utf8")} >>\nstream\n${content}\nendstream`,
  ]

  let pdf = "%PDF-1.4\n"
  const offsets = [0]
  for (let i = 0; i < objects.length; i += 1) {
    offsets.push(Buffer.byteLength(pdf, "utf8"))
    pdf += `${i + 1} 0 obj\n${objects[i]}\nendobj\n`
  }
  const xrefOffset = Buffer.byteLength(pdf, "utf8")
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (let i = 1; i < offsets.length; i += 1) {
    pdf += `${String(offsets[i]).padStart(10, "0")} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`
  return Buffer.from(pdf, "utf8")
}
