import { getClientPortalData } from "@/lib/client-portal"

export default async function ClientInvoicesPage() {
  const { client, invoices } = await getClientPortalData()
  if (!client) return <div className="rounded-2xl bg-amber-50 p-8 text-amber-900">This client account is not linked to a client record yet.</div>
  const total = invoices.reduce((sum, invoice) => sum + invoice.amount, 0)
  const outstanding = invoices.filter(i => i.status !== "PAID").reduce((sum, invoice) => sum + invoice.amount, 0)
  return <div className="mx-auto max-w-7xl space-y-7"><div><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Client Portal</p><h1 className="mt-1 text-3xl font-bold">Invoices & Billing</h1><p className="mt-2 text-sm text-slate-500">Review invoices, amounts and payment status. Payment actions remain controlled by Accounts.</p></div><div className="grid gap-4 sm:grid-cols-2"><Metric label="Total invoiced" value={`₹${total.toLocaleString()}`} /><Metric label="Outstanding" value={`₹${outstanding.toLocaleString()}`} /></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Invoice</th><th className="p-4">Amount</th><th className="p-4">Due date</th><th className="p-4">Status</th><th className="p-4">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{invoices.map(invoice => <tr key={invoice.id} className="text-sm"><td className="p-4 font-semibold text-slate-900">#{invoice.id.slice(-8).toUpperCase()}</td><td className="p-4 font-semibold">₹{invoice.amount.toLocaleString()}</td><td className="p-4 text-slate-600">{invoice.dueDate.toLocaleDateString()}</td><td className="p-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${invoice.status === "PAID" ? "bg-emerald-50 text-emerald-700" : invoice.status === "OVERDUE" ? "bg-red-50 text-red-700" : "bg-amber-50 text-amber-700"}`}>{invoice.status}</span></td><td className="p-4"><button className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-semibold text-slate-600 print:hidden" onClick={() => {}} aria-label="Invoice actions">View / Print from browser</button></td></tr>)}{invoices.length===0 && <tr><td colSpan={5} className="p-12 text-center text-sm text-slate-500">No invoices have been issued to this client account.</td></tr>}</tbody></table></div></div></div>
}
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">{label}</p><p className="mt-2 text-2xl font-bold text-slate-900">{value}</p></div> }
