import Link from "next/link"

const features = [["People", "Employee profiles, attendance, leave, onboarding, notifications and role-aware access."], ["Operations", "Task assignment, workload visibility and operational monitoring for managers."], ["Projects", "Project creation, delivery timelines and centralized project visibility."], ["Finance & CRM", "Clients, invoices, domains and business records in one controlled workspace."], ["Reports", "Management dashboards that turn operational data into actionable visibility."], ["Security", "Server-side authorization, encrypted sensitive data, audit logs and protected credentials."]]

export default function FeaturesPage() {
  return <PublicLayout title="Everything your company needs to operate." eyebrow="Platform capabilities"><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-400">Company OS connects the operational systems that teams normally spread across disconnected tools.</p><div className="mt-14 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{features.map(([title, text]) => <article key={title} className="rounded-2xl border border-white/10 bg-white/[0.04] p-7"><div className="mb-6 flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-500/15 font-bold text-indigo-300">{title[0]}</div><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-6 text-slate-400">{text}</p></article>)}</div></PublicLayout>
}

function PublicLayout({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <main className="min-h-screen bg-[#07111f] text-white"><header className="mx-auto flex h-20 max-w-7xl items-center justify-between border-b border-white/10 px-6"><Link href="/" className="font-black tracking-wide">COMPANY OS</Link><nav className="flex items-center gap-5 text-sm text-slate-400"><Link href="/features" className="text-white">Features</Link><Link href="/security" className="hover:text-white">Security</Link><Link href="/about" className="hover:text-white">About</Link><Link href="/#sign-in" className="rounded-lg bg-white px-4 py-2 font-bold text-slate-950">Sign in</Link></nav></header><div className="mx-auto max-w-7xl px-6 py-20"><p className="text-sm font-bold uppercase tracking-[0.2em] text-indigo-300">{eyebrow}</p><h1 className="mt-3 max-w-4xl text-5xl font-black tracking-tight sm:text-6xl">{title}</h1>{children}</div></main> }
