import Link from "next/link"
import { prisma } from "@/lib/prisma"
import { requireClientPortal } from "@/lib/client-portal"
import { PageHeader } from "@/components/ui/PageHeader"
import { Card } from "@/components/ui/Card"
import { StatusBadge } from "@/components/ui/StatusBadge"
import { Button } from "@/components/ui/Button"

export default async function ClientInvoiceDetailPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { client } = await requireClientPortal()
  if (!client) {
    return (
      <div className="mx-auto max-w-xl py-12">
        <Card className="border-amber-200 bg-amber-50/50 p-6 text-amber-900 text-sm">
          This client account is not linked to a client company profile yet.
        </Card>
      </div>
    )
  }

  const { id } = await params
  const invoice = await prisma.invoice.findFirst({ where: { id, clientId: client.id } })

  if (!invoice) {
    return (
      <div className="mx-auto max-w-xl py-12">
        <Card className="border-rose-200 bg-rose-50/50 p-6 text-rose-900 text-sm">
          Invoice not found or access is restricted.
        </Card>
      </div>
    )
  }

  return (
    <div className="mx-auto max-w-3xl space-y-8 font-sans">
      <PageHeader
        category="Invoice Statement"
        title={`Invoice #${invoice.id.slice(-8).toUpperCase()}`}
        description="Official billing statement generated by Company OS finance operations."
        actions={
          <Link href="/dashboard/client/invoices">
            <Button variant="outline" size="md">
              ← Back to Invoices
            </Button>
          </Link>
        }
      />

      <Card className="p-8 shadow-md">
        {/* Invoice Header */}
        <div className="flex flex-col gap-6 border-b border-slate-100 pb-6 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-slate-400">Billed Entity</p>
            <h2 className="mt-1 text-2xl font-extrabold text-slate-900">{client.company}</h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Attn: {client.name} · {client.email}
            </p>
          </div>
          <div className="text-left sm:text-right">
            <p className="text-xs font-bold uppercase tracking-wider text-slate-400 mb-1">Status</p>
            <StatusBadge status={invoice.status} size="md" />
          </div>
        </div>

        {/* Invoice Amounts Breakdown */}
        <div className="grid grid-cols-1 gap-6 py-8 sm:grid-cols-3 border-b border-slate-100">
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-slate-400">Total Billed</p>
            <p className="mt-1.5 text-2xl font-black text-slate-900">
              ₹{invoice.amount.toLocaleString()}
            </p>
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-slate-400">Due Date</p>
            <p className="mt-1.5 font-bold text-slate-800 text-sm font-mono">
              {new Date(invoice.dueDate).toLocaleDateString()}
            </p>
          </div>
          <div>
            <p className="text-xs font-bold uppercase tracking-wider text-slate-400">Issue Date</p>
            <p className="mt-1.5 font-bold text-slate-800 text-sm font-mono">
              {new Date(invoice.createdAt).toLocaleDateString()}
            </p>
          </div>
        </div>

        {/* Payment / Contact Information */}
        <div className="pt-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 text-xs text-slate-500">
          <p>
            For payment reconciliation or wire inquiries, please contact our finance desk directly.
          </p>
          <Link href="/dashboard/client/messages">
            <Button variant="primary" size="sm" className="bg-cyan-600 hover:bg-cyan-700 whitespace-nowrap">
              Message Accounts Desk →
            </Button>
          </Link>
        </div>
      </Card>
    </div>
  )
}
