import { getClientPortalData } from "@/lib/client-portal"

export default async function ClientTasksPage({ searchParams }: { searchParams: Promise<{ project?: string }> }) {
  const { tasks, client } = await getClientPortalData()
  if (!client) return <div className="rounded-2xl bg-amber-50 p-8 text-amber-900">This client account is not linked to a client record yet.</div>
  const { project } = await searchParams
  const visible = project ? tasks.filter(task => task.projectId === project) : tasks
  return <div className="mx-auto max-w-7xl space-y-7"><div><p className="text-sm font-semibold uppercase tracking-wider text-indigo-600">Client Portal</p><h1 className="mt-1 text-3xl font-bold">Project Tasks</h1><p className="mt-2 text-sm text-slate-500">Read-only visibility into delivery work assigned to your projects.</p></div><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-left"><thead className="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th className="p-4">Task</th><th className="p-4">Project</th><th className="p-4">Priority</th><th className="p-4">Status</th><th className="p-4">Deadline</th><th className="p-4">Owner</th></tr></thead><tbody className="divide-y divide-slate-100">{visible.map(task => <tr key={task.id} className="text-sm"><td className="p-4"><p className="font-semibold text-slate-900">{task.title}</p><p className="mt-1 max-w-md text-xs text-slate-500">{task.description || "—"}</p></td><td className="p-4 text-slate-600">{task.project?.name || "—"}</td><td className="p-4"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{task.priority}</span></td><td className="p-4"><span className="rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700">{task.status.replace(/_/g, " ")}</span></td><td className="p-4 text-slate-600">{task.deadline?.toLocaleDateString() || "—"}</td><td className="p-4 text-slate-600">{task.user?.name || "Team"}</td></tr>)}{visible.length===0 && <tr><td colSpan={6} className="p-12 text-center text-sm text-slate-500">No tasks are currently linked to this view.</td></tr>}</tbody></table></div></div></div>
}
